branch-defaults:
  develop:
    environment: routepals-dev
  traivisCICD:
    environment: routepals-dev
environment-defaults:
  routepals-dev:
    branch: null
    repository: null
global:
  application_name: routepals
  default_ec2_keyname: my-keypair
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
