branch-defaults:
  develop:
    environment: RoutePals-dev
    group_suffix: null
  tempDev:
    environment: RoutePals-dev
environment-defaults:
  RoutePals-dev:
    branch: null
    repository: null
global:
  application_name: RoutePals
  branch: null
  default_ec2_keyname: shashank
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
