# Generated by Django 4.2.16 on 2024-11-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="deleted_at",
        ),
    ]
