# Generated by Django 4.2.16 on 2024-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
