# Generated by Django 4.2.16 on 2024-11-10 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_userreport"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserReport",
            new_name="UserReports",
        ),
    ]
