# Generated by Django 4.2.16 on 2024-11-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
