# Generated by Django 4.2.16 on 2024-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_userprofile_file_name_userprofile_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_emergency_support",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
