# Generated by Django 4.2.16 on 2024-11-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_userprofile_is_emergency_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_emergency_support",
            field=models.BooleanField(default=False),
        ),
    ]
