# Generated by Django 4.2.16 on 2024-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="desired_companions",
            field=models.IntegerField(default=0),
        ),
    ]
