# Generated by Django 4.2.16 on 2024-11-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_trip_desired_companions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("SEARCHING", "Searching for companion"),
                    ("MATCHED", "Matched"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SEARCHING",
                max_length=20,
            ),
        ),
    ]
