# Generated by Django 4.2.16 on 2024-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_userlocation_panic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocation",
            name="panic_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
